# TTS Configuration with Beam Search and Self-Rewarding
# Test-Time Scaling configuration for PRISM reasoning framework

# ============================================================================
# MODEL CONFIGURATION
# ============================================================================
actor_model_dir: "/home/user/workspace/models/PRISM-CoT"  # Path to the model directory
generate_mode: "vllm"  # Options: "vllm" or "local"
server_url: "http://localhost:8000/v1"  # VLLM server URL

# ============================================================================
# GENERATION PARAMETERS
# ============================================================================
temperature: 1.0
top_p: 0.9
top_k: 50
max_tokens: 1024
seed: 42

# ============================================================================
# TTS-SPECIFIC PARAMETERS
# ============================================================================
# Beam Search Configuration
beam_width: 5           # Number of candidates to keep at each step
num_candidates: 8       # Number of initial candidates to generate at each step
final_candidates: 1     # Number of complete responses for best-of-N selection

# Step-specific token limits for the 4 reasoning steps
step_max_tokens:
  PROBLEM: 512     # Problem understanding and intention analysis
  CAPTION: 512     # Image description and visual analysis
  REASONING: 1024  # Logical reasoning and step-by-step analysis
  OUTPUT: 512      # Final answer and conclusion

# Self-Rewarding Configuration
use_step_rewards: true   # Use step-wise self-rewarding during beam search
use_final_rewards: true  # Use final self-rewarding for best-of-N selection
mode: "outcome"          # Evaluation mode

# ============================================================================
# DATA PATHS
# ============================================================================
train_prompt_path: # your prompt here
output_path: "./results"
log_file: "./logs/tts_beam_search.log"

# ============================================================================
# PROCESSING CONFIGURATION
# ============================================================================
# Threading Configuration
worker_num: 1
worker_prompt_num: 50

# Cache Configuration
use_cache: false
cache_dir: "./cache"

# ============================================================================
# EVALUATION PARAMETERS (inherited from MCTS base config)
# ============================================================================
max_depth: 4  # 4 steps: PROBLEM, CAPTION, REASONING, OUTPUT
c: 1.5        # UCB exploration parameter (used in evaluation)
