swift rlhf \
    --rlhf_type dpo \
    --model Your PRISM-SFT model here \
    --model_type llava1_6_mistral_hf \
    --train_type lora \
    --dataset /dev/shm/SafeVL-DPO/DPO_swift.jsonl \
    --torch_dtype bfloat16 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --learning_rate 3e-5 \
    --lora_rank 32 \
    --lora_alpha 128 \
    --target_modules all-linear \
    --gradient_accumulation_steps 16 \
    --eval_steps 30 \
    --save_steps 50 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 8192 \
    --output_dir output \
    --warmup_ratio 0.05 \
    --attn_impl flash_attn \
    --freeze_vit true 